- Setup/UpgradeSchema.php
- etc/module.xml
> Pull request 1

- composer.json
Tags is not a valid key, it should be `keywords`; https://getcomposer.org/doc/04-schema.md#keywords
> Fix keywords in composer.json

- composer.json
Makes it easier to test 1.x releases
> Set branch alias to 1.0-dev

- view/frontend/web/js/lib/myparcel.js
Deselect freeshipping if myparcel method is chosen
> Fix IE onestepcheckout select mp method

- Model/Sales/Repository/PackageRepository.php
Select the correct database tabel for the mailbox package
> fix: Select the correct database tabel for mailbox package

- view/frontend/layout/default_head_blocks.xml
Fix for Critical error getting options.min.css #99
> Edit src link for options.css

- Model/Sales/MagentoCollection.php
> Fix table prefix

- Model/Checkout/Carrier.php
- Model/Checkout/ShippingInformationManagementPlugin.php
- Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php
this solution is for users with MagePlaza OneStepCheckout version 2.6.1
> check if MyParcel method is selected

- Model/Rate/Result.php
fix : Warning: count(): Parameter must be an array or an object that implements
Countable in
/home/stropda2/public_html/vendor/myparcelnl/magento/Model/Rate/Result.php
on line 271*
> check if items/products exist

- view/frontend/web/js/checkout/shipping_method/show-myparcel-shipping-method.js
check if there is a 2nd address field. issue: cannot read property 'get' of undefined
> check if street 1 exist

- Model/Sales/TrackTraceHolder.php
code verwijderd die niet wordt gebruik voor het aanmaken van Wereld zendingen
> deleted unnecessary code

- Model/Checkout/Carrier.php
- Model/Quote/Checkout.php
- Model/Rate/Result.php
- etc/adminhtml/system.xml
- etc/config.xml
- i18n/en_US.csv
- i18n/nl_NL.csv
- view/frontend/web/js/checkout/shipping_method/show-myparcel-shipping-method.js
- view/frontend/web/js/lib/myparcel.js
- view/frontend/web/template/checkout/options.html
It is no longer possible to use pickup express, since November
> Remove Pickup Express

- Model/Quote/Checkout.php
- Model/Sales/Repository/PackageRepository.php
- Model/Source/DropOffDelayDays.php
- Setup/UpgradeData.php
Set a delivery day delay in product settings and get the highest delay day for the delivery options.
> Set a deliver day delay in product settings

- Model/Sales/TrackTraceHolder.php
- etc/adminhtml/system.xml
- i18n/nl_NL.csv
> add product_id, product_name, product_qty to label description

- Model/Quote/Checkout.php
the productDelay was overuled by generalDelay
> the productDelay was overuled by generalDelay

- Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php
- Model/Sales/Repository/PackageRepository.php
- Model/Sales/TrackTraceHolder.php
- Observer/CreateConceptAfterInvoice.php
- etc/adminhtml/system.xml
- etc/config.xml
- etc/events.xml
- i18n/nl_NL.csv
- virtual products
- country of origin
- create concept after invoice
- variable label description
> Add several options

- Helper/Data.php
- Model/Sales/TrackTraceHolder.php
- composer.json
> Delivery is on the next day, even if MyParcel checkout is not used

- Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php
- Model/Sales/Repository/DeliveryRepository.php
> fix: error on placing order with a non-postnl shipping method

- Helper/Data.php
- Model/Sales/Package.php
- Model/Sales/PackageInterface.php
- Model/Sales/Repository/PackageRepository.php
- Model/Sales/TrackTraceHolder.php
- Model/Source/DefaultOptions.php
> fix: package type when different package types are in the shopping cart

- Api/PackageTypeInterface.php
- Model/Checkout/PackageType.php
- Model/Quote/Checkout.php
- etc/di.xml
- etc/webapi.xml
- view/frontend/web/js/model/checkout.js
- view/frontend/web/js/view/delivery-options.js
> My 23991 show correct packagetypes for selected country

- etc/adminhtml/system.xml
> fix: options signature and only recipient should not depend on 18 check

- Controller/Adminhtml/Shipment/CreateAndPrintMyParcelTrack.php
- README.md
> Change shipment massaction to use shipment collection

- Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php
fix misplaced bracket, split from https://github.com/myparcelnl/magento/pull/510
> fix: delivery options check

- Observer/CreateConceptAfterInvoice.php
pickup the make concept option from the right place, split from https://github.com/myparcelnl/magento/pull/510
> fix: configuration path

- view/frontend/templates/email/shipment/track.phtml
check for existence of tracking url as well as empty value, split from original https://github.com/myparcelnl/magento/pull/510
> fix: tracking url

- view/frontend/web/js/view/delivery-options.js
- when myparcel shipping method is not selected the options must not refresh.
> fix: the ability to not select a myparcel shipping option

- Model/Order/Email/Container/TrackIdentity.php
- Model/Order/Email/Sender/TrackSender.php
- composer.json
- view/frontend/layout/sales_email_order_shipment_track.xml
- view/frontend/templates/email/shipment/track.phtml
> fix: use correct track trace template

- Model/Sales/MagentoOrderCollection.php
- because some orders will not be sent with myparcel, they has no myparcel status. In some cases, a magento shipment has been made and will cause errors
> fix: some shipments have no myparcel status

- Model/Sales/MagentoOrderCollection.php
> fix: if inventoryApi does not exist you should not use the sourceItem

- Helper/Data.php
- Resolves #613 
- Resolves #615
> fix: error delivery date is too early

- Block/Sales/NewShipment.php
- Block/Sales/NewShipmentForm.php
- Model/Sales/TrackTraceHolder.php
- Observer/NewShipment.php
- i18n/nl_NL.csv
- view/.eslintrc
- view/adminhtml/templates/new_shipment.phtml
- view/adminhtml/web/js/new-shipment.js
> fix: choose carrier packagetypes options logically

- Setup/UpgradeData.php
> fix: fix schema update failure

- Helper/Checkout.php
- Model/Quote/Checkout.php
> fix: only get available options for carriers

- Cron/UpdateStatus.php
> fix: have cronjob update shipment status

- Ui/Component/Listing/Column/TrackAndTrace.php
> fix: remove php deprecation warning

- Setup/Uninstall.php
- composer.json
> fix: remove attributes on uninstall

- Model/Sales/Repository/PackageRepository.php
> fix: mailbox works with kilo setting on php 8.1

- Model/Sales/MagentoOrderCollection.php
- Observer/SalesOrderStatusHistoryObserver.php
- Setup/UpgradeSchema.php
- composer.json
- etc/events.xml
- etc/extension_attributes.xml
> feat(fulfilment): add order notes

- Setup/Methods/Select.php
Needs myparcelnl/sdk#...
Resolves #..., resolves #...
> fix: fix deprecated functionality

- Setup/Migrations/ReplaceDisableCheckout.php
- Setup/Migrations/ReplaceFitInMailbox.php
- Setup/QueryBuilder.php
- Setup/UpgradeSchema.php
- fix(migration): honor database table prefix
- fix(migration): honor does not fit in mailbox setting
> fix(migration): honor database table prefix

- view/frontend/web/js/model/shipping-save-processor-default.js
Needs myparcelnl/sdk ~v7.8.0
Resolves #774
> fix(checkout): restore payload extender functionality

- Helper/ShipmentOptions.php
> fix(order-mode): allow export with carrier specific options

- view/frontend/web/js/model/checkout.js
> fix(checkout): show delivery options for tablerate when appropriate

- Observer/SalesOrderStatusHistoryObserver.php
> fix(ordernote): bail early without order

- Block/Sales/NewShipmentForm.php
- Helper/Data.php
- etc/adminhtml/system.xml
- etc/config.xml
- i18n/en_US.csv
- i18n/nl_NL.csv
- view/adminhtml/web/template/grid/order_massaction.html
- view/frontend/web/js/view/delivery-options.js
> feat: add carrier dpd

- Helper/Checkout.php
- Model/Quote/Checkout.php
- view/frontend/web/js/model/checkout.js
- view/frontend/web/js/view/delivery-options.js
> refactor(checkout): differentiate between method code and carrier code

- Model/Order/Email/Sender/TrackSender.php
> fix: allow observer to use transport object

- Helper/ShipmentOptions.php
- Model/Sales/MagentoOrderCollection.php
- i18n/en_US.csv
- i18n/fr_FR.csv
- i18n/nl_NL.csv
- view/frontend/web/js/model/checkout.js
> fix: implement regression feedback

- view/frontend/web/js/model/checkout.js
- view/frontend/web/js/view/delivery-options.js
> fix(checkout): prevent delivery options from disappearing

- composer.json
> chore: use sdk 7.9.1

- view/frontend/web/js/view/delivery-options.js
> fix(checkout): prevent missing street from blocking delivery options

- Model/Sales/TrackTraceHolder.php
- composer.json
> feat: add state to consignment

- view/frontend/web/js/view/delivery-options.js
> fix: use both address lines for street name

- Model/Settings/AccountSettings.php
> fix: fix php 8.2 deprecation error

- Helper/Checkout.php
- Model/Quote/Checkout.php
- Model/Source/PriceDeliveryOptionsView.php
- etc/adminhtml/system.xml
- i18n/en_US.csv
- i18n/nl_NL.csv
- view/frontend/web/js/view/delivery-options.js
> feat: add price surcharge option

- Block/Sales/NewShipmentForm.php
- Controller/Adminhtml/Settings/CarrierConfigurationImport.php
- Model/Quote/Checkout.php
- Model/Rate/Result.php
- Model/Sales/Repository/PackageRepository.php
- Model/Source/DefaultOptions.php
- etc/adminhtml/system.xml
- view/adminhtml/templates/new_shipment.phtml
Needs myparcelnl/sdk#474
INT-357
> feat: add international bbp

- i18n/en_US.csv
- i18n/fr_FR.csv
- i18n/nl_NL.csv
- view/frontend/web/js/view/delivery-options.js
> fix(checkout): stabilise choosing pickup point

- i18n/en_US.csv
- i18n/fr_FR.csv
- i18n/nl_NL.csv
> feat: change large package name

- Model/Source/DefaultOptions.php
> fix: allow exporting without delivery options

- Model/Quote/Checkout.php
> fix(checkout): honor monday delivery setting

- Model/Checkout/Carrier.php
- Model/Quote/Checkout.php
- Model/Sales/Repository/PackageRepository.php
- i18n/en_US.csv
- i18n/fr_FR.csv
- i18n/nl_NL.csv
> fix: allow package type mailbox when postnl is disabled

- Model/Checkout/ShippingMethods.php
> fix(checkout): use backwards compatible delivery options

- Helper/Checkout.php
> fix(checkout): show delivery options also when totalprice is chosen

- Model/Sales/Repository/PackageRepository.php
> fix(checkout): show delivery options even with missing mailbox settings

- Model/Quote/Checkout.php
> fix(checkout): take carrier specific mailbox weight into account

- composer.json
> chore: change minimum php version to 7.1

- Helper/Data.php
- view/adminhtml/templates/new_shipment.phtml
> feat: add receipt code for belgium

- Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php
> fix: prevent random error messages from halting shipment creation

- Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php
> feat: show error message when received from api

- view/frontend/web/js/view/delivery-options.js
> feat(checkout): unselect delivery options when other method is chosen

- Helper/Data.php
- Model/Sales/TrackTraceHolder.php
> fix: ensure product weight is correctly exported to backoffice

- composer.json
- etc/adminhtml/system.xml
- etc/di.xml
Needs myparcelnl/sdk#538
INT-1069
> fix: show ups settings

- etc/adminhtml/system.xml
- etc/config.xml
- i18n/fr_FR.csv
- i18n/nl_NL.csv
- src/Block/System/Config/Form/DeliveryCostsMatrix.php
- src/Model/Quote/Checkout.php
- src/Service/DeliveryCosts.php
- view/adminhtml/web/css/config/delivery_costs_matrix/style.css
- view/adminhtml/web/js/delivery-costs-matrix.js
- view/frontend/web/js/model/checkout.js
This also adds a clarification to the max weight text: the weight must be entered in gram.
INT-1090
> feat(v5): add setting to respect free shipping or not
