myparcelnl/magento

- Setup/UpgradeData.php
- composer.json
When there is a update about a product option Magento replaced the database row with the data in the migration.
The migration in https://github.com/myparcelnl/magento/pull/321 don't work and hide the BBP and the DPZ options
> Add correct migration

- Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php
This fixes a bug a customer of ours encountered where this action showed the error "No shipment can be made with this order. Shipments can not be created if the status is On Hold or if the product is digital." when attempting to print the label for certain orders. Even though this error was shown, a shipment was created, but the tracking information was incomplete. 
As far as I understand the issue arises because the, while the shipments are created in the database, the in-memory representations of the orders (that are checked in the orderCollection::hasShipment() function) are not updated with these new shipments. Resulting in the hasShipment call returning false. By reloading the order collection the in-memory references are made up-to-date and the system seems to work.
> Reload Order Collection after creating shipments

- Controller/Adminhtml/Shipment/CreateAndPrintMyParcelTrack.php
While working on a bug for a customer that uses this plugin I noticed this bug in the error handling code. The getMessages function returns a Collection object that does not implement a Countable interface. It does however have a getItems() function that returns an array which is countable. Alternatively the Collection class also contains a getCount function which could be used.
> Error handling fix

- Controller/Adminhtml/Order/CreateAndPrintMyParcelTrack.php
- Model/Sales/TrackTraceHolder.php
- Some consumers put too many spaces between the numbers and letters of a postcode.
- In addition, there are also consumers that place a space after the postcode. All these extra spaces must be removed, so that the export functions properly.
> fix: trim spaces from postcode

- i18n/nl_NL.csv
Added the necessary translations in nl_NL file. Also changed two instances of 'map' to 'kaart'
> fix: display correct translations in order grid

- Observer/NewShipment.php
- README.md
We were receiving the following error when creating a shipment from the backend:
```
Uncaught TypeError: Return value of MyParcelNL\Sdk\src\Adapter\DeliveryOptions\AbstractDeliveryOptionsAdapter::getCarrier() must be of the type string or null, bool returned in vendor/myparcelnl/sdk/src/Adapter/DeliveryOptions/AbstractDeliveryOptionsAdapter.php:88
```
> Fix false carrier causing type errors

- Block/Sales/OrderAction.php
- Block/Sales/ShipmentAction.php
- Model/Checkout/PackageType.php
- Model/Quote/SaveOrderBeforeSalesModelQuoteObserver.php
- Model/Sales/MagentoCollection.php
- Model/Sales/MagentoOrderCollection.php
- composer.json
In de gecompileerde code wordt bij OrderAction en ShipmentAction de consignment geinstantieerd lijkt het, en dit kunnen we ook proefondervindelijk vaststellen. Door de BaseConsigment te gebruiken gaat dit goed (itt de AbstractConsignment). Er wordt geen specifieke consignment doorgegeven, alleen worden methods gebruikt.
> fix: use BaseConsignment where you need an instance

- view/frontend/web/js/view/delivery-options.js
Needs myparcelnl/sdk#...
Resolves #..., resolves #...
> fix: don't render delivery options when already visible

- Plugin/Magento/Sales/Api/Data/OrderExtension.php
We're getting this error a lot;
```
MyParcelNL\Magento\Plugin\Magento\Sales\Api\Data\OrderExtension::useEntityId(): Argument #1 ($entityId) must be of type int, string given, called in /data/web/releases/20230124154227/vendor/myparcelnl/magento/Plugin/Magento/Sales/Api/Data/OrderExtension.php on line 65
```
`useEntityId` expects an int; `private function useEntityId(int $entityId): array`
However, you're exploding a string and not casting it;
```
$explodePath = explode('/', $path ?? '');
[$searchColumn, $searchValue] = $this->useEntityId(end($explodePath));
```
So I added `(int)` to cast the numeric value to an int.
> fix: prevent type error in use entity id

- Plugin/Magento/Sales/Api/Data/OrderExtension.php
When using an order prefix in Magento (like `ORD00000123456` instead of just `00000123456`), the `$searchValue` is cast to an `int`.
This presumably done to avoid SQL injections, so I changed it to using the second parameter of `where()` so Magento escapes it for us and SQL injections are avoided. This way, we can use strings to look for orders with an increment ID instead of only a numeric value.
The resulting query previously resulted in fetching _all_ orders since the `$searchValue` became `0`. Because we have 500k+ orders, this resulted in an out of memory error.
> Fix: use correct way to inject search value

- Block/Sales/View.php
I got this error;
Fix proof:
```
php > $data['date'] = null;
php > $dateTime = date('d-m-Y H:i', strtotime($data['date']));
PHP Deprecated:  strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in php shell code on line 1
PHP Stack trace:
PHP   1. {main}() php shell code:0
PHP   2. strtotime($datetime = NULL) php shell code:1
Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in php shell code on line 1
Call Stack:
32.4666     603888   1. {main}() php shell code:0
32.4666     603888   2. strtotime($datetime = NULL) php shell code:1
php > $dateTime = date('d-m-Y H:i', strtotime($data['date'] ?? ''));
php > var_dump($dateTime);
php shell code:1:
string(16) "01-01-1970 00:00"
```
Resolves #739
> prevent php 8.1 deprecation notice in strtotime

- Model/Sales/Package.php
> fix: only set country if currentCountry has value

- Model/Source/DigitalStampWeightOptions.php
- Setup/Migrations/ReplaceDpzRange.php
- Setup/UpgradeData.php
> feat: add digital stamp weight range

- Block/Sales/NewShipmentForm.php
- Helper/Data.php
- etc/adminhtml/system.xml
- etc/config.xml
- i18n/en_US.csv
- i18n/nl_NL.csv
- package.json
- view/adminhtml/web/template/grid/order_massaction.html
- view/frontend/web/js/view/delivery-options.js
Needs myparcelnl/sdk#463
INT-181
> feat: add carrier ups

- Model/Sales/MagentoOrderCollection.php
Needs myparcelnl/sdk#465
INT-330
> fix(fulfilment): export phonenumber and weight

- Model/Quote/Checkout.php
- Model/Sales/Package.php
- Model/Sales/Repository/PackageRepository.php
- Model/Sales/TrackTraceHolder.php
- composer.json
- etc/adminhtml/system.xml
- i18n/en_US.csv
- i18n/nl_NL.csv
- view/adminhtml/web/template/grid/order_massaction.html
- view/frontend/web/js/view/delivery-options.js
> feat: add package type package small

- Setup/UpgradeData.php
> fix(migration): allow migration to run with invalid scopes present

- Block/Sales/NewShipment.php
- Block/Sales/NewShipmentForm.php
- Helper/Data.php
- Helper/ShipmentOptions.php
- Model/Sales/TrackTraceHolder.php
- Model/Source/DefaultOptions.php
- i18n/fr_FR.csv
- i18n/nl_NL.csv
- view/adminhtml/templates/new_shipment.phtml
> fix(export): allow signature or only_recipient for be

- Model/Quote/Checkout.php
- view/frontend/web/js/model/checkout.js
It was not possible to toggle mailbox package per carrier.
INT-496
> fix(checkout): fix mailbox options

- composer.json
Required for https://github.com/myparcelnl/magento/pull/856 which is already released and broken.
> fix: use country country codes from sdk

- Block/Sales/NewShipment.php
- Helper/ShipmentOptions.php
- Model/Sales/TrackTraceHolder.php
- Model/Source/DefaultOptions.php
- composer.json
> fix(export): restore automate shipment options settings

- Helper/Checkout.php
- Model/Quote/Checkout.php
- Model/Rate/Result.php
- etc/adminhtml/system.xml
- etc/config.xml
- i18n/fr_FR.csv
- i18n/nl_NL.csv
- view/frontend/web/js/view/delivery-options.js
> feat: add delivery fee

- Model/Sales/Repository/PackageRepository.php
- Model/Source/DefaultOptions.php
- Model/Source/LargeFormatOptions.php
- i18n/en_US.csv
- i18n/fr_FR.csv
- i18n/nl_NL.csv
> fix: remove weight from large format option

- i18n/en_US.csv
- i18n/fr_FR.csv
- i18n/nl_NL.csv
- src/Block/System/Config/Form/DeliveryCostsMatrix.php
- src/Service/DeliveryCosts.php
- view/adminhtml/web/css/config/delivery_costs_matrix/style.css
- view/adminhtml/web/js/delivery-costs-matrix.js
Converting the conditions to an object with type and value enables the user to stash conditions of the same type, e.g. make a rule that is applied to multiple countries, or multiple carriers.
This PR also updates the layout of the UI and adds an option to show / hide the original textarea, enabling users to simply copy-paste the rules between installations.
Resolves: [INT-1105](https://internal.jira.dmp.zone/browse/INT-1105) and [INT-814](https://internal.jira.dmp.zone/browse/INT-814?atlOrigin=eyJpIjoiNDAxMmY3ZTUxNWJhNDZhOThiZDJjY2FkMDNmZGVmNjEiLCJwIjoiaiJ9)
[INT-1105]: https://myparcelnl.atlassian.net/browse/INT-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[INT-814]: https://myparcelnl.atlassian.net/browse/INT-814?atlOrigin=eyJpIjoiNWRk …
> feat: update condition to object with type and value
